export const SERVER_PORT:string = process.env.PORT || '3000';
export const {
  JWT_SECRET,
  DATABASE_HOST,
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_DB,
  DEV_DATABASE_HOST,
  DEV_DATABASE_USER,
  DEV_DATABASE_PASSWORD,
  DEV_DATABASE_DB,
} = process.env;
